// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/zheyuanf/ecommerce-tiktok/app/frontend/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproducsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.CasbinCheck(),
	}
}

func _deleteproductMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.CasbinCheck(),
	}
}

func _createproductMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.CasbinCheck(),
	}
}
