// Code generated by hertz generator.

package checkout

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/zheyuanf/ecommerce-tiktok/app/frontend/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...

	return []app.HandlerFunc{
		middleware.JWTAuth(),
		middleware.CasbinCheck(),
	}
}

func _checkoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkout0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutresultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutwaitingMw() []app.HandlerFunc {
	// your code...
	return nil
}
