volumes:
  log_data:
    driver: local

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  consul:
    image: "hashicorp/consul:latest"
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    ports:
      - "9000:9000" # MinIO Web UI
      - "9001:9001" # MinIO 控制台 UI
    command: server /data --console-address ":9001"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - log_data:/logs/frontend
    command: -config.file=/etc/promtail/config.yml
  frontend:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.frontend-shotcut
    ports:
      - 8080:8080
    environment:
      - GO_ENV=dev
      - SESSION_SECRET=sdf23joi1
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./app/frontend/conf/dev:/opt/ecommerce-tiktok/frontend/conf/dev
      - log_data:/opt/ecommerce-tiktok/frontend/log
  user:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=user
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/user/conf/dev:/opt/ecommerce-tiktok/user/conf/dev
  order:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=order
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/order/conf/dev:/opt/ecommerce-tiktok/order/conf/dev
  email:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=email
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/email/conf/dev:/opt/ecommerce-tiktok/email/conf/dev
  payment:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=payment
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/payment/conf/dev:/opt/ecommerce-tiktok/payment/conf/dev
  product:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=product
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/product/conf/dev:/opt/ecommerce-tiktok/product/conf/dev
  checkout:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=checkout
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/checkout/conf/dev:/opt/ecommerce-tiktok/checkout/conf/dev
  cart:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=cart
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/cart/conf/dev:/opt/ecommerce-tiktok/cart/conf/dev
  auth:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=auth
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/auth/conf/dev:/opt/ecommerce-tiktok/auth/conf/dev
  storage:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc-shotcut
      args:
        - SVC=storage
    environment:
      - GO_ENV=dev
    depends_on:
      consul:
        condition: service_started
    volumes:
      - ./app/storage/conf/dev:/opt/ecommerce-tiktok/storage/conf/dev
